---
title: "IS607 - Week 8"
author: "Rob Hodde"
date: "March 20, 2016"
output: html_document
---

##Assignment - Working with XML and JSON in R##

Pick three of your favorite books on one of your favorite subjects. At least one of the books should have more
than one author. For each book, include the title, authors, and two or three other attributes that you find
interesting.

Take the information that you've selected about these three books, and separately create three files which
store the book's information in HTML (using an html table), XML, and JSON formats (e.g. "books.html",
"books.xml", and "books.json"). 

To help you better understand the different file structures, I'd prefer that you
create each of these files "by hand" unless you're already very comfortable with the file formats.

Write R code, using your packages of choice, to load the information from each of the three sources into
separate R data frames. Are the three data frames identical?

Your deliverable is the three source files and the R code. If you can, package your assignment solution up into
an .Rmd file and publish to rpubs.com. [This will also require finding a way to make your three text files
accessible from the web].


```{r}

library(XML)
library(RCurl)
library(jsonlite)
library (plyr)

#read the html file
sURL <- "https://raw.githubusercontent.com/LovinSpoonful/IS607-WEEK8/master/books.html"
sHTML <- getURL(sURL)
tHTML <- htmlTreeParse(sHTML)   #this is just for reference, to show the structure


# parse html
doc = htmlParse(sHTML, asText=TRUE)
plain.text <- xpathSApply(doc, "//text()[not(ancestor::script)][not(ancestor::style)][not(ancestor::noscript)][not(ancestor::form)]", xmlValue)
v <- capture.output(cat(paste(plain.text, collapse = " ")))
dfHTML <- data.frame(v)
dfHTML


#XML Example:
sURL <- "https://raw.githubusercontent.com/LovinSpoonful/IS607-WEEK8/master/books.xml"
xData <- getURL(sURL)
xDoc <- xmlParse(xData)
lXML <- xmlToList(xData)
dfXML <- ldply (lXML, data.frame)
print(dfXML)


#JSON example:
sURL <- "https://raw.githubusercontent.com/LovinSpoonful/IS607-WEEK8/master/books.json"
l = jsonlite::fromJSON(sURL)
df <- ldply (l, data.frame)
print(df)


```

The dataframes are not identical.


